### ISSUE TITLE
Is it possible to run this in the background of an Android application?

### ISSUE THREAD

**Issue by nbendall34** [FragLand/minestat#50] opened 2021-01-04 19:01 UTC
I'm trying to make an Android app for checking a Minecraft server's status. Is it possible to run the Java code in the background?

**Comment by nbendall34** [comment] 2021-01-04 19:04
After writing this, I started an Android Studio project and imported the code to run from the console for now. These are my results:
![image](https://user-images.githubusercontent.com/33398449/103569566-7266ec80-4ebf-11eb-9033-de4b1e77f014.png)

![image](https://user-images.githubusercontent.com/33398449/103569600-7f83db80-4ebf-11eb-9360-ff9b75cc09ef.png)

The second image shows output from the code, meaning it ran. But mc.hypixel.net:25565 is reachable. What could be causing this to show that it's not?

**Comment by BlueTree242** [comment] 2021-01-04 22:01
you are right, `ms.isServerUp` is always false

**Comment by ldilley** [comment] 2021-01-04 22:56
The Java code should run fine within an Android application. The correct port to use is the TCP port that players connect to (not query which is UDP based). The symptom being observed here is due to `mc.hypixel.net` only responding to SLP 1.7 requests. The Java implementation of MineStat supports up to SLP 1.6. See issue #43 for details. I just confirmed that the server replies OK using SLP 1.7 from the PHP implementation per the output below:

```
<17:47:26> (~/projects/minestat/PHP)
[ldilley@genesis] :) {5032}$ php example.php
Minecraft server status of mc.hypixel.net on port 25565:<br>Server is online running version Requires MC 1.8 / 1.16 with 118195 out of 141000 players.<br>Message of the day:  <br>Latency: 64ms<br>
```

**Comment by nbendall34** [comment] 2021-01-05 15:41
Right okay, I understand why the servers I tested wouldn't respond to MineStat Java now. Java looks the closest to supporting SLP 1.7, at a estimate, how close would you say MineStat Java is to supporting SLP 1.7?

**Comment by ldilley** [comment] 2021-01-06 05:51
I've no estimate for you unfortunately. Issue #21 was specifically added to track SLP 1.7 support for the various languages. One complication is that there is no native [JSON](https://www.w3schools.com/whatis/whatis_json.asp) support in Java. This would require writing the functionality to parse JSON data or using a 3rd-party library. I was hoping to avoid the use of external dependencies for this project, but it just may be the best approach in the context of Java. Further research is needed to determine what JSON libraries are available for Java and if any of their licenses would permit use in this project.

Feel free to keep this issue open. I can use it to reply with my findings.

**Comment by nbendall34** [comment] 2021-01-06 11:00
Ah okay, so I'm assuming that when MineStat queries the server, and gets a response, that response is in the form of JSON? If so, [Google's GSON library](https://github.com/google/gson) could provide you with what you need. It's under the Apache license, which I believe allows you to use and modify the code as long as you credit them? 

Someone must have already written code to parse JSON in Java without the use of external libraries, you can't have been the first to do this, and I doubt you're the last!

**Comment by ldilley** [comment] 2021-02-09 01:47
The response is in JSON format for SLP 1.7. Responses for previous SLP versions were not in JSON. Yes; Google's GSON library would work as would JSON Simple (https://github.com/fangyidong/json-simple or https://github.com/cliftonlabs/json-simple). I'll close this issue since issues #21 and #43 are both open to track SLP 1.7 support.

**Closed by ldilley** 2021-02-09 01:47 UTC
Labels: question

**Comment by ldilley** [comment] 2021-03-04 03:29
@nbendall34: As an FYI, SLP 1.7 support was added in PR #74 (f61a903) if you still need it.
