### ISSUE TITLE
'Server is offline'

### ISSUE THREAD

**Issue by amorphine** [FragLand/minestat#19] opened 2018-12-24 07:10 UTC
Hello!
Thanks for the code. But I have faced an issue, that one of the servers can not be queried with the code provided. The server version is 1.7.10. The IP address and the Port are 164.132.201.216:25560.
Meanwhile this service works nice https://mcsrvstat.us/server/164.132.201.216:25560 which means the server can be queried.
Please help me to understand what's wrong. Thanks

### Actual behavior/symptoms
'Server if offline'

### Steps to reproduce behavior/symptoms
Pass 164.132.201.216:25560 as server option

### MineStat version
Latest JS and Go implementations

### Operating system
Ubuntu 18.04

**Comment by ldilley** [comment] 2018-12-24 08:33
Greetings, @amorphine. Thank you for the report. This actually impacts all MineStat implementations (C#, Go, Java, Ruby, Py, etc.) To be honest, I've kind of gotten away from the Minecraft scene. However, I will still look at this more after the holidays. The problem is that the SLP implementation employed by the minecraftonly.ru server software does not respond to the packets being sent. The fix would be to send the expected packet data which would be:

```
1. 0xFE
2. 0x01
3. 0xFA
4. 0x00 0x4D 0x00 0x43 0x00 0x7C 0x00 0x50 0x00 0x69 0x00 0x6E 0x00 0x67 0x00 0x48 0x00 0x6F 0x00 0x73 0x00 0x74
5. 7 + length of remote hostname in UTF-16BE format as a short
6. 0x4A
7. Remote hostname as UTF-16BE encoded string
8. Remote port as an int
```

Right now, MineStat only sends 0xFE and 0x01 and, in this case, the remote server never responds. MineStat then reports the server as unresponsive. I hope this explanation helps. I've tested a preliminary fix in Java, but need time to clean it up and look at the other implementations.

**Comment by amorphine** [comment] 2018-12-24 09:19
@ldilley Thank you much!

**Comment by ldilley** [comment] 2019-01-09 08:20
Issues #20 and #21 have been created to track the addition of newer server query protocols.

**Comment by Raideerke** [comment] 2019-01-09 11:49
Oh lol :) Good to see a maintained project :) Good luck, @ldilley !

**Comment by ldilley** [comment] 2019-01-27 08:14
Update: b9f7af9 contains the Ruby fix. Now, it must be ported to all the other languages...

**Comment by sinhpn92** [comment] 2020-11-11 08:49
I have Java to get the info. But It still have same error :((

**Comment by ldilley** [comment] 2021-02-09 01:57
Closing this issue since issues #20, #21, and #43 are being used to track missing SLP support.

**Closed by ldilley** 2021-02-09 01:57 UTC
Labels: bug
